name: Flutter CI

on:
  push:
    branches:
      - aes-algorithm  # Adjust this to your default branch if necessary
  pull_request:
    branches:
      - aes-algorithm

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'  # Specify the Flutter version, e.g., '2.10.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/lcov.info
          flags: flutter
          name: code-coverage-report
          token: 2f59bcbb-7263-4e0c-9a37-e710e39705bb  # Add this to your GitHub secrets
          fail_ci_if_error: true

      - name: Build APK
        run: flutter build apk --release  # Build APK for Android

      # Optionally, you can add a step to upload the APK as an artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: my_app_apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign  # Build iOS without code signing

      # Optionally, you can add a step to upload the iOS build as an artifact
      - name: Upload iOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: my_app_ios
          path: build/ios/iphoneos/*.app  # Adjust the path according to your iOS build output